- name: Test Play
  hosts: all
  gather_facts: False
  serial: 1


  tasks:
    - name: "Get the Hostname "
      command: hostname
      register: result1
    - debug : msg=" Hostname {{ result1 }}"
    
    - name: "Create file"
      command: touch ansibleTest
